### ISSUE TITLE
Responds to bots

### ISSUE THREAD

**Issue by Natemo6348** [Topscientist/ArtysModertion#3]
Whenever a bot says something like "angry" the bot responds to it

**Comment by Topscientist** [comment]
Hi, I am not quite sure what you mean, Currently the bot posts a new message in the channel pro you following the message that triggered the “Cheer Up” creature, if you mean that the bot reply’s to the message, then good idea and I will try to get that feature implemented soon

**Comment by Topscientist** [comment]
_Reads Again_ Ah, So do you mean that it also responds to bots, yep, I am aware of that, I am currently looking into ways of how to orient this from happening, I have only seen it once in the past and I am trying to find a way so that it doesn’t happen, Thanks for the suggestion and I will keep this feed open just in case you have any other comments/questions

**Comment by Natemo6348** [comment]
Oh ok, I didn't know you were aware, I just thought of testing it randomly so that's how I found out lol

**Comment by Topscientist** [comment]
👍

**Comment by Topscientist** [comment]
Just a quick note; I have my bot on the Discord Bots verification queue and some slightly more pressing issues have been highlighted, I will get back to this when I have resolved these issues, Sorry

**Comment by Topscientist** [comment]
Ok, worked on a fix that is accepted by the code, So I will run a unit test then push out the new code, Thanks for highlighting this!

**Comment by Topscientist** [comment]
Ok, acctually let me backtrack, My fix didn't work

**Comment by Topscientist** [comment]
Okie, Fixed the issue, Thanks again for highlighting this!
